export const REQUEST_RACERS = 'REQUEST_RACERS'
export const RECEIVE_RACERS = 'RECEIVE_RACERS'

export const REQUEST_PREV_PAGE = 'REQUEST_PREV_PAGE'
export const RECEIVE_PREV_PAGE = 'RECEIVE_PREV_PAGE'

export const REQUEST_NEXT_PAGE = 'REQUEST_NEXT_PAGE'
export const RECEIVE_NEXT_PAGE = 'RECEIVE_NEXT_PAGE'

export const SET_NEXT_PAGE = 'SET_NEXT_PAGE'
export const SET_PREV_PAGE = 'SET_PREV_PAGE'
