export const REQUEST_RACERS = 'REQUEST_RACERS'
export const RECEIVE_RACERS = 'RECEIVE_RACERS'

export const REQUEST_PREV_PAGE = 'REQUEST_PREV_PAGE'
export const REQUEST_NEXT_PAGE = 'REQUEST_NEXT_PAGE'

export const SET_NEXT_PAGE = 'SET_NEXT_PAGE'
export const SET_PREV_PAGE = 'SET_PREV_PAGE'

export const REQUEST_SINGLE_RACER = 'REQUEST_SINGLE_RACER'
export const RECEIVE_SINGLE_RACER = 'RECEIVE_SINGLE_RACER'
